---
title: "Papers"
author: "Янина Е.А."
date: "13 01 2020"
output:
  word_document: default
  html_document: default
bibliography: ref.bib
link-citations: yes
csl: gost-r-7-0-5-2008-numeric-iaa.csl
biblio-style: numeric
---

<!-- (Название статьи) -->
<!-- - на ккакой вопрос хотели ответить авторы? -->
<!-- - что они измерили и как измерили? -->
<!-- - что нашили авторы? -->
<!-- - что думают что нашли? -->

<!-- - подытожить центральное утверждение -->
<!-- - отметить детали относящиеся к НАШЕМУ исследованию -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 9-10.01.2020

[@шендяпин2008использование]

# 13.01.2020

Авторы статьи ставили своей целью... [@непопалов2015спортивная].

[фамилия0000первое]

[@березина2019изменение]

# 15.01.2020

Совершенствование и развитие спортсмена имеет генетическую основу. В литературе приводятся предварительные данные 16 генетических маркеров, связаных с предрасположенностью к конкретным видам спорта (case-control designs), а 12 маркеров были связаны с чертами личности (genotype-phenotype designs). Существует широкий разброс в экспериментальных дизайнах и типах выборки, и результаты еще предстоит воспроизвести в независимых выборках. Следует отметить, что каждый локус ДНК может объяснить только очень небольшую долю фенотипической дисперсии (например, от ~ 0,1% до ~ 1%), так что для обнаружения ассоциаций могут потребоваться как очень большие размеры выборки, так и комбинации локусов генов. представляет интерес. Поскольку полиморфизмы ДНК для когнитивных способностей и личностных черт спортсменов не полностью объясняют известную наследуемость таких черт, необходимо также учитывать другие формы вариации, такие как редкие мутации и эпигенетические маркеры (то есть стабильные и наследственные изменения в экспрессии генов) [@valeeva2019psychogenetics].

# 16.01.2020

[@аллахвердов2014за].

# 20.01.2020

В психологии спорта при измерении показателей используются произвольные метрики. Переход от субъективной исследовательской оценки к фактическому значению -- затрудняется. Размер эффекта при интерпретации произволных метрик неуловим [@andersen2007but].


#

 [@].

# 22.01.2020

[текст статьи](https://journals.sagepub.com/doi/abs/10.1177/0018720819839817)  [@martin2019impact].

В статье рассматривается как опытные-испытуемые и испытумые-новички совмещают визуальную и аудиальную информацию. ..... [@khacharem2019representation].

Проведен онлайн опрос 493 спортсменов. [@wahl2019psychological].

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6400145/ [@fuentes2019differences].

https://link.springer.com/article/10.1007/s10648-019-09464-6 [@feldon2019cognitive].

https://psycnet.apa.org/record/2018-48471-001 [@campbell2019pupillometry].

При выполнении двигательной и когнитивной задачи могз и мышцы конкурируют за одни и те же ресурмы (энергию) __Когда двигательная и когнитивная задача выполняются одновременно, мозг и мышцы должны конкурировать за одни и те же ресурсы (например, энергию и т. Д.), Которые известны как помехи. Эгоистичная гипотеза мозга (Peters et al., 2004) предполагает, что мозг определяет свои собственные потребности в глюкозе по сравнению с периферическими органами, такими как скелетные мышцы. До сих пор неясно, какое влияние это вмешательство оказывает на когнитивные и / или физические характеристики. Цель этого исследования состояла в том, чтобы изучить гипотезу эгоистичного мозга и выяснить, как явная расстановка приоритетов влияет на распределение ресурсов и выполнение двойной задачи. Используя схему исследования между субъектами, 32 участника были случайным образом распределены в группу без приоритетов, с когнитивным приоритетом или группой с физическим приоритетом. NeuroTracker, программа восприятия когнитивной тренировки и эргометр цикла были использованы для измерения когнитивных и физических показателей, соответственно. Участники выполнили 5 оценок: 2 когнитивных, 1 прогнозируемый максимум VO2 и 1 двойное задание. Во время выполнения двойного задания участники завершили 3 сеанса NeuroTracker, пока ездили на велосипеде на велоэргометре. Односторонние специальные тесты ANOVA и Tukey показали, что у группы с физическим приоритетом RPM были значительно выше в 8-секундные моменты времени по сравнению с группой с когнитивным приоритетом. Однако при сравнении показателей RPM и скорости визуального отслеживания во всех трех группах показатели физической работоспособности оставались относительно стабильными в ходе оценки физических и двойных задач. Все группы испытывали улучшения в своих показателях скорости визуального отслеживания по мере прохождения исследования. Мы предлагаем, чтобы оценки, предшествующие выполнению двойной задачи, выполнялись как учебные занятия и, следовательно, ограниченное вмешательство двойной задачи.__[@petersen2019duel].

https://www.degruyter.com/view/j/ammin.2019.104.issue-6/am-2019-Ed104611/am-2019-Ed104611.xml
https://www.sciencedirect.com/science/article/abs/pii/S0031938418309351
https://link.springer.com/article/10.1007/s11682-018-0020-0
https://arxiv.org/abs/1904.08155
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6400145/
https://www.sciencedirect.com/science/article/abs/pii/S0031938419305700

http://j.uniyar.ac.ru/index.php/vyrgu/article/view/871

http://elib.sportedu.by/bitstream/handle/123456789/3185/Konferencija_tom-2-2019%20229-233.pdf?sequence=1&isAllowed=y

http://elib.bsu.by/bitstream/123456789/222568/1/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D1%84%D0%B5%D1%80%D0%B0%D1%82-%D0%90%D1%81%D1%82%D1%80%D0%B5%D0%B9%D0%BA%D0%BE%20%D0%9D.%D0%A1..pdf

#  23.01.2020

 [@].

# 25.01.2020 

Развлекательное чтение -- [@клейн2017муки].

#  28.01.2020

(Класная статья по следам "подкаменной"). [@meredith2018review].

#  29.01.2020

Успешное выполнение стрельбы из лука зависит от ряда параметров. Стрельба из лука представляет собой статичный вида спорта на точность, требующий соответствующей подготовки как во время, так и перед соревнованиями. Соревновательная деятельность в стрельбе реализуется на фоне: напряжения, беспокойства и волнений, поэтому для достижения успеха в спорте необходима правильная психическая адаптация и сосредоточенность [1]. Исследования показали, что некоторые психологические элементы, такие как чувство беспокойства, стресс и недостаток внимания, затрудняют спортивные результаты, особенно в стрельбе из лука, в которой умственная прочность является одним из ключей к его успешному принятию [2]. Однако стоит отметить, что требование определенного психологического навыка варьируется от одного вида спорта к другому. Особенность определенного вида спорта предъявляет уникальную потребность в психологической подготовке спортсменов, занимающихся спортом. Поэтому уместно оценить психологические элементы, необходимые для конкретного вида спорта  [@musa2019psychological].

Понятие "исполнительные функции" (когнитивный контроль) на сегодняшний день не имеет четкого определения. Существуют ряд теорий исполнительных функций, которые можно разделить на три группы: однокомпонентные, основанные на конструктах и многокомпонентные теории. Основной сложностью в изучении сознательного контроля является отсутствие универсального средства измерения. Обычно исследуются отдельные аспекты исполнительных функций посредством отдельых тестов тестов. Так же упускается обстоятельство, что исполнительные функции нигде не проявляют себя изолированно от других психических процессов. Также отмечается, что в исследованиях упускается связь когнитивного контроля с мотивационной, личностной и смысловой сферами психики. Для исследователей из области спортивной психологии представляет интерес ... [@алексеев2010понятие].

Исследования исполнительных функций  [@виленская2016исполнительные].


# 06.02.2020  

Психологическая классификация видов спортивной деятельности [@девишвили2014информационно].
 
 
# 07.02.2020  

http://lib.sportedu.ru/DocQuery.idc?DocQuerID=9557781&DocTypID=NULL&QF=TPFK&St=1&Pg=20&Cd=Win&Tr=0&On=0&Op=NEW&Author=%CC%E0%E7%ED%E8%F7%E5%ED%EA%EE&DocQuerItmID=

На основе двигательных реакций испытуемых делается предположение об особенностях коркового механизма формирования двигательного навыка. В процессе обучения двигательному навыку у гимнастов различного уровня подготовки по 5-бальной шкале оценивалась каждая попытка исполнения движения в процессе всего хода формирования навыка. Строилась кривая хода формирования двигательного навыка. Для описания движения выделены звенья. Ведущим звеном называлась часть двигательного акта, придающая движению его специфический характер. Остальныее части движения считались вспомогателными звеньями. https://drive.google.com/file/d/0BzF1KVTWzThZd2d2bTJxY2tCS1U/view [@мазниченко1964зависимость].

# 10.02.2020  
# 11.02.2020  
# 12.02.2020  

[@balk2020recovery].

# 13.02.2020  
# 14.02.2020  

<!-- Надо возобновить проект.. И не "каждый день", а просто с некоторой регулярностью. В своём темпе. -->

# 10.08.2020

<!-- https://ssc-phil.univie.ac.at/fileadmin/user_upload/s_philosophie/Studien/MA_MeiCogSci/MEiCogSci-Conference-2020-Proceedings.pdf#page=85 -->

Analysis of Stress in Chess Players Through Physiological Responses

Игра в шахматы традиционно использовалась в качестве модели для изучения познавательных процессов таких как решение задач, принятие решений, память и других. Стресс испытывамый игроками исследуется в меншей степени, хотя стрессовое состояние может повлиять на когнитивную деятельность спортсмена и его результативность.


Целью этого исследования было изучение у игроков в шахматы физиологического ответа на стресс вызванный недостатком времени на обдумывание (time pressure), ситуации на шахматной доске, ошибками и другими факторами. Это исследование подводит к созданию модели по обнаружению стресса на основе алгоритмов машинного обучения, которая будет предсказывать стрессирован ли шахматист. Кроме того, авторы статьи стремились выястить есть ли влияние зарегистрированного стресса на качество игры.


В исследовании приняли участие 44 игрока в шахматы (со средним возрастом 35±16) сыгравших 103 игры. Испытуемые были субъективно здоровы. Средний рейтинг ЭЛО составил 2108 ± 154. Исследование проводилось на значимых соревнованиях в Словении, которые продлились 9 дней.

На протяжении всей шахматной партии (около 5 часов) непрерывно регистрировались физиологические показатели: ЧСС, КГР и температура кожи) по средством наручного устройства (датчиков на запастьи), а также шахматрая позиция и время при помощи электронной шахматной доски. В конце каждой игры испытуемые заполняли опросник о настроении в целом и наиболее напряженных моментах в партии.


Для предобработки физиологических данных использовался пайплайн описанный в статье. Для оценки шахматной позиции использовался шахматный движок "Stockfish 11". Для проверки гипотезы и создания модели определения стресса использовались различные методы статистики и алгоритмы машинного обучения.


Качественные изменения стрессовой реакции видны на решающих этапах игры.

Полученные результаты можно использовать для разроботки инструментов помогающих игроку отслеживать стрессовые состояния и изучить собственные реакции на стресс, а также помочь тренерам в тренировочном периоде сспортивной подготовки [@mencin2020analysis].

# 13.08.2020
<!-- https://www.mdpi.com/1660-4601/17/1/46 -->

https://www.mdpi.com/1660-4601/17/1/46

В исследовании анализировались отличия в спектральной мощности ЭЭГ (тета, альфа и бета) между участниками которые выиграли (группа выигрыша) и проигравшими (группа проигрыша) в трех разных игровых условиях, где противник был: с таким же рейтингом Эло (100% игры), с рейтингом Эло на 25% превышающем их собственный (125% игры), и рейтингом на 25% ниже (75% игры). Записывалась исходная ЭЭГ и ЭЭГ на протяжении партии в шахматы. 14 игроков мужского пола (возраст: 35.36 ± 13.77 и рейтинг Эло: 1921 ± 170) играли партии с контролем времени 3 минуты, с добавлением 2 секунд за ход. На трех уровнях сложности (75%, 100% и 125%) игрались по две партии (черными и белыми) на каждом уровне. Группа выигравших продемонстрировала большую мощность тета-активности в 
лобной, центральной и теменной областях ("frontal, central, and posterior brain regions" **или не теменой а задней?**) с увеличением сложности игры. Кроме того, мощность альфа-спектра принимала более высокие значения в 125% играх по сравнению с 75% играми в C3, T3, T4, T5, и T6 отведениях. Группа проигравших показала снижение ,бета- и альфа-спектра в лобной, центральной, теменно-височной и затылочной облаcтях, при снижении рейтинга противника. Анализ межгрупповых различий показал большую мощность тета-спектра в группе проигравших по сравнению с группой выигравших в C3, T5, T6, P4, и Pz отведениях. Таким образом, группа выигравших адаптировалась на каждом уровне мощности увеличивая мощность тета-спектра в лобных, центральных и теменных областях головного мозга, соответственно гипотезе эффективности. В группе проигравших таких изменений не наблюдалось. Можно предположить, что увеличение мощности альфа спектра на протяжении сложных игр по сравнению с более легкими могло быть вызвано идеацией и дивергентным мышлением, поскольку игроки искали альтернативные решения против более опытных игроков (creative ideation, divergent thinking) [@fuentes2020chess].


Апарат: Enobio device, a wireless electrode system(?)

Схема: 17 scalp locations, including: frontal (Fz, F3, F4, F7, and F8), central (Cz, C3, and C4), temporal (T3, T4, T5, and T6), parietal (Pz, P3, and P4), and occipital (O1 and O2), according to the International 10–20 system.
Референт -- на обоих ушах =)
Софт: EEGLAB toolbox (MATLAB), SPSS

https://ieeexplore.ieee.org/abstract/document/6869515


# 17.08.2020
<!-- https://link.springer.com/article/10.1007/s11245-020-09715-0 -->

Взаимодействие между автоматическими процессами и процессами относящимися к когнитивному контролю является (по предположению авторов данной статьи) отличительной чертой умения (навыка) от привычки, что и обеспечивает гибкость. Их взаимодействие не является полностью иерархическим и статическим, а скорее гетерархично и динамично. Кроме того, взаимодействие зависит от репрезентаций и внутренних моделей, того на сколько они подробны и структурированы, а также от сопутствующего развития процессов метаконтроля, которые используются для формирования навыка.

В июне 2019 года Рафаэль Надаль выиграл Открытый чемпионат Франции по теннису, установив новый рекорд - двенадцать побед на этом турнире. Многие считают его величайшим теннисистом на грунтовых кортах всех времен и все согласны с тем, что он высококвалифицированный спортсмен. Но в чем именно заключается этот навык? Безусловно, без скорости, силы и общей физической подготовки Надаль не был бы чемпионом, которым он является. Ясно, однако, что этих качеств недостаточно. Можно быть в превосходной форме и при этом не знать, как играть в теннис, не говоря уже о том, чтобы быть искусным в этом. Что еще нужно, чтобы стать опытным теннисистом?

Совершенно очевидно, что для приобретения навыка требуется (много) практики. Как подчеркивают Haith и Krakauer (2018), практика приводит к улучшению способности быстро выбирать подходящие действия и точно их выполнять, в то же время приводя к большей эффективности, т.е. к снижению когнитивной нагрузки (cognitive load), необходимой для выполнения задания. Однако эти свойства присущи не только умениям. Они также характерны для формирования (хороших) привычек.

Что же тогда отличает умение от привычных действий? Философы, когда они обращают внимание на это различие, склонны противопоставлять осмысленное действие механическому. Психологи, в свою очередь, обычно характеризуют привычки как автоматические, негибкие и обусловленные стимулами действия, и хотя в навыках есть элементы автоматизма, навыки остаются целенаправленными и очень гибкими.

Для понимания что представляет из себя навык необходимо дать определение феномену интеллекта. Авторы этой статьи считают гибкость основным компонентом интеллекта. Умелое поведение (Skilled behavior) чувствительно к целям агента и контексту в котором он действует. Агент обладающий сформированными умениями закономерно реагирует на новые или необычные ситуации. Характеристикой умелого действия ...

<!-- В разд. 2, мы начинаем с определения различия между привычками и навыками и предлагаем краткую общую характеристику интеллекта навыков, понимаемых как гибкость. В разд. 3 мы опираемся на психологическую литературу, чтобы сформулировать и нюансировать различие между автоматическими и когнитивными процессами управления; в частности, мы обсуждаем градации автоматического и когнитивного контроля. В разд. В разделе 4 мы проводим различие между иерархическим и гетерархическим взглядами на взаимодействие между этими процессами управления и смотрим на некоторые существующие гибридные версии квалифицированных действий и обрисовываем общие обязательства тех, кто придерживается гетерархического подхода. Мы отмечаем, что одним из ограничений этих описаний является то, что они мало говорят о типах психологических репрезентаций, используемых экспертами, поэтому они, по крайней мере, являются неполными. В разд. 5, мы утверждаем, что то, что отличает высококвалифицированных игроков от менее опытных исполнителей и новичков (например, профессионального теннисиста от любителя или новичка), - это структурная сложность и точность их мысленных представлений в их области знаний. Мы проводим различие между двумя типами мысленных представлений у экспертов: представлениями, поддерживающими выполнение действия, и представлениями, поддерживающими выбор действия. Наконец, в разд. 6 мы предлагаем набросок того, как опытный исполнитель обретает способность к тому, что мы называем метаконтролем, то есть способность успешно выбирать между более когнитивными и более автоматическими режимами управления в отношении как выбора действий, так и их выполнения. Мы предполагаем, что метапознание играет центральную роль в этом процессе, и в заключение предполагаем, что моделирование метаконтроля таким образом может дать нам естественный способ объяснения отличительной феноменологии навыка. -->

Разница между привычками и навыками становится очевидной, когда вместо противопоставления привычек повседневным навыкам (например, завязывания шнурков) мы противопоставляем их профессиональным навыкам, продемонстрированным Надалем как теннисистом. Теннисист выполнивший миллионы подборов мяча и подач, не нарабатывает полный автоматизм, а каждый раз заново выстраивает последовательность действий, оценив за доли секунды траекторию и скорость мяча, а затем принимает решение о том как действовать. 

Привычка вырабатывается, а усвоение навыка требуе тренировки.





[@pacherie2020beyond].

<!-- #  

 [@]. -->

# Литература